# Generated by Django 3.2.5 on 2021-07-25 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('ltp', models.FloatField()),
                ('change', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('open', models.FloatField()),
                ('qty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('sector', models.CharField(max_length=250)),
                ('shares_outstanding', models.FloatField()),
                ('market_price', models.FloatField()),
                ('change', models.FloatField()),
                ('last_trade_on', models.CharField(max_length=250)),
                ('weeks_52_high', models.FloatField()),
                ('weeks_52_low', models.FloatField()),
                ('day_120_average', models.FloatField()),
                ('year_1_yeild', models.FloatField()),
                ('eps', models.CharField(max_length=250)),
                ('pe_ratio', models.FloatField()),
                ('book_value', models.FloatField()),
                ('pbv', models.FloatField()),
                ('dividend', models.CharField(max_length=250)),
                ('bonus', models.CharField(max_length=250)),
                ('right_share', models.CharField(max_length=250)),
                ('day_30_avg_volume', models.FloatField()),
                ('market_capitalization', models.FloatField()),
                ('trade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nepseAPI.trade')),
            ],
        ),
    ]
